export { default as About } from './About';
export { default as Home } from './Home';
export { default as NotFound } from './NotFound';
export { default as Play } from './Play';
export { default as Work } from './Work';
export { default as Featured } from './Featured';
export { default as Signin } from './Signin';
export { default as Signup } from './Signup';
export { default as Dashboard } from './Dashboard';